import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,ExternalLink,Search,X} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';

interface Row {canonical_id:string;name:string;system:string;laterality:string;scope:string;granularity?:string;crosswalk_review?:string;uberon?:string;fma?:string;best_available:string|null;candidates:string[];grouped_candidates?:string[];sources?:string[];coverage_kind?:string;female_reference:boolean;female_segmented_unreviewed:boolean;female_segmented_grouped_partial?:boolean;female_measured:boolean;template_only:boolean}
const SOURCE_LABEL:Record<string,string>={'denver-vhf':'Denver VHF','hra-female':'HRA female','tcia':'TCIA 003','bodyparts3d':'BodyParts3D (male)'};
export function Coverage({open,onClose,onInspect}:{open:boolean;onClose:()=>void;onInspect:(source:string,id:string)=>void}) {
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[bestOnly,setBestOnly]=useState(false);
 useEffect(()=>{if(!open||rows.length)return;const controller=new AbortController();fetch('/atlases/coverage-matrix.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Coverage could not be loaded');return r.json();}).then(data=>{if(!Array.isArray(data))throw Error('Invalid coverage catalog');setRows(data as Row[]);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[open,rows.length]);
 const filtered=useMemo(()=>rows.filter(r=>(!query||`${r.name} ${r.canonical_id} ${r.uberon??''} ${r.fma??''}`.toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||filter==='measured'&&r.female_measured||filter==='reference'&&r.female_reference||filter==='segmented'&&r.female_segmented_unreviewed||filter==='template'&&r.template_only||filter==='missing'&&!r.candidates.length||filter==='multi'&&(r.sources?.length??0)>1||filter==='partial'&&!!r.grouped_candidates?.length||filter==='crosswalk'&&!!r.crosswalk_review&&!r.crosswalk_review.startsWith('no-crosswalk'))),[rows,query,filter]);
 const pages=Math.max(1,Math.ceil(filtered.length/60));
 const inspect=(candidate:string)=>{const separator=candidate.indexOf(':');onInspect(candidate.slice(0,separator),candidate.slice(separator+1));};
 const evidence=(r:Row)=>r.female_measured?'Female measured · VHF donor':r.female_segmented_unreviewed?'Female CT · unreviewed':r.female_reference?'Female reference':r.template_only?'Male template':r.grouped_candidates?.length?'Partial · grouped CT label only':'No direct geometry';
 return <Sheet open={open} onOpenChange={value=>{if(!value)onClose();}}><SheetContent className="coverage-sheet" showCloseButton={false}>
  <header><div><SheetTitle>Coverage</SheetTitle><SheetDescription>{rows.length.toLocaleString()} catalog entries · imported sources · UBERON/FMA crosswalk with OLS evidence, anatomist review pending</SheetDescription></div><button aria-label="Close coverage" title="Close coverage" onClick={onClose}><X size={20}/></button></header>
  <div className="coverage-filters"><label><Search size={16}/><input aria-label="Search coverage" value={query} placeholder="Structure, UBERON or FMA identifier" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><select aria-label="Coverage category" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All entries</option><option value="measured">Female measured · VHF</option><option value="segmented">Female CT · unreviewed</option><option value="reference">Female reference</option><option value="multi">Several sources (merged by crosswalk)</option><option value="partial">Partial · grouped CT label</option><option value="crosswalk">Crosswalk-resolved labels</option><option value="template">Male template only</option><option value="missing">No direct geometry</option></select><label className="coverage-toggle"><input type="checkbox" checked={bestOnly} onChange={e=>setBestOnly(e.target.checked)} aria-label="Show only the best available source per structure"/>Best available only</label></div>
  {error&&<p role="alert">{error}</p>}
  <div className="coverage-table"><table><thead><tr><th>Structure</th><th>Evidence</th><th>Geometry</th></tr></thead><tbody>{filtered.slice(page*60,(page+1)*60).map(r=><tr key={r.canonical_id}><td><strong>{r.name}</strong><span>{r.canonical_id}{r.granularity&&r.granularity!=='individual'?` · ${r.granularity}`:''}</span>{r.crosswalk_review&&!r.crosswalk_review.startsWith('no-crosswalk')&&<span className="coverage-review">{r.crosswalk_review}</span>}</td><td>{evidence(r)}<span>{r.system}{r.sources&&r.sources.length>1?` · ${r.sources.length} sources`:''}</span></td><td>{r.candidates.length?(bestOnly&&r.best_available?[r.best_available]:r.candidates).map(candidate=><button key={candidate} className={candidate===r.best_available?'best':''} onClick={()=>inspect(candidate)} title={`${candidate}${candidate===r.best_available?' · best available by source priority':''}`}>{SOURCE_LABEL[candidate.split(':')[0]]??candidate.split(':')[0]}<ExternalLink size={13}/></button>):<span>{r.scope==='source-hierarchy-concept'?'Hierarchy concept':r.grouped_candidates?.length?'':'Missing'}</span>}{!bestOnly&&r.grouped_candidates?.map(candidate=><button key={candidate} className="partial" onClick={()=>inspect(candidate)} title={`${candidate} · grouped label covering both sides; partial coverage`}>{SOURCE_LABEL[candidate.split(':')[0]]??candidate.split(':')[0]} · grouped<ExternalLink size={13}/></button>)}</td></tr>)}</tbody></table></div>
  <footer><span>{filtered.length.toLocaleString()} entries</span><div><button aria-label="Previous coverage page" title="Previous page" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ArrowLeft size={17}/></button><span>{page+1} / {pages}</span><button aria-label="Next coverage page" title="Next page" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}><ArrowRight size={17}/></button></div><a href="/atlases/coverage-matrix.json" download>JSON</a></footer>
 </SheetContent></Sheet>;
}
