import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,ExternalLink,Search,X} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';

interface Row {canonical_id:string;name:string;system:string;laterality:string;scope:string;best_available:string|null;candidates:string[];female_reference:boolean;female_segmented_unreviewed:boolean;female_measured:boolean;template_only:boolean}
export function Coverage({open,onClose,onInspect}:{open:boolean;onClose:()=>void;onInspect:(source:string,id:string)=>void}) {
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0);
 useEffect(()=>{if(!open||rows.length)return;const controller=new AbortController();fetch('/atlases/coverage-matrix.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Coverage could not be loaded');return r.json();}).then(data=>{if(!Array.isArray(data))throw Error('Invalid coverage catalog');setRows(data as Row[]);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[open,rows.length]);
 const filtered=useMemo(()=>rows.filter(r=>(!query||`${r.name} ${r.canonical_id}`.toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||filter==='measured'&&r.female_measured||filter==='reference'&&r.female_reference||filter==='segmented'&&r.female_segmented_unreviewed||filter==='template'&&r.template_only||filter==='missing'&&!r.candidates.length)),[rows,query,filter]);
 const pages=Math.max(1,Math.ceil(filtered.length/60));
 const inspect=(candidate:string)=>{const separator=candidate.indexOf(':');onInspect(candidate.slice(0,separator),candidate.slice(separator+1));};
 return <Sheet open={open} onOpenChange={value=>{if(!value)onClose();}}><SheetContent className="coverage-sheet" showCloseButton={false}>
  <header><div><SheetTitle>Coverage</SheetTitle><SheetDescription>{rows.length.toLocaleString()} catalog entries · imported sources</SheetDescription></div><button aria-label="Close coverage" title="Close coverage" onClick={onClose}><X size={20}/></button></header>
  <div className="coverage-filters"><label><Search size={16}/><input aria-label="Search coverage" value={query} placeholder="Structure or identifier" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><select aria-label="Coverage category" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All entries</option><option value="measured">Female measured · VHF</option><option value="segmented">Female CT · unreviewed</option><option value="reference">Female reference</option><option value="template">Male template only</option><option value="missing">No direct geometry</option></select></div>
  {error&&<p role="alert">{error}</p>}
  <div className="coverage-table"><table><thead><tr><th>Structure</th><th>Evidence</th><th>Geometry</th></tr></thead><tbody>{filtered.slice(page*60,(page+1)*60).map(r=><tr key={r.canonical_id}><td><strong>{r.name}</strong><span>{r.canonical_id}</span></td><td>{r.female_measured?'Female measured · VHF donor':r.female_segmented_unreviewed?'Female CT · unreviewed':r.female_reference?'Female reference':r.template_only?'Male template':'No direct geometry'}<span>{r.system}</span></td><td>{r.candidates.length?r.candidates.map(candidate=><button key={candidate} onClick={()=>inspect(candidate)} title={candidate}>{candidate.split(':')[0]}<ExternalLink size={13}/></button>):<span>{r.scope==='source-hierarchy-concept'?'Hierarchy concept':'Missing'}</span>}</td></tr>)}</tbody></table></div>
  <footer><span>{filtered.length.toLocaleString()} entries</span><div><button aria-label="Previous coverage page" title="Previous page" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ArrowLeft size={17}/></button><span>{page+1} / {pages}</span><button aria-label="Next coverage page" title="Next page" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}><ArrowRight size={17}/></button></div><a href="/atlases/coverage-matrix.json" download>JSON</a></footer>
 </SheetContent></Sheet>;
}
